# Generated by Django 3.1.4 on 2021-02-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alum',
            new_name='alumni_info',
        ),
        migrations.RenameField(
            model_name='alumni_info',
            old_name='stu_name',
            new_name='student_name',
        ),
    ]
